### ISSUE TITLE
add community guidelines and a developer guide

### ISSUE THREAD

**Issue by Chilipp** [kuadrat/data-slicer#10]
according to the JOSS review criteria, you need

> **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I could not find them in the docs or the source code repository. see https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors for some help

### Disclaimer
this issue is part of the review in https://github.com/openjournals/joss-reviews/issues/2969

**Comment by Chilipp** [comment]
hey @kuadrat! thanks for adding these community guidelines! A crucial thing concerning the scholarly effort of this package is the reusability and extensibility of your framework, and I think the contributing guide place an important role here. But there is another aspect that is still missing, that is a guide how to write a plugin. It's kind of a developer guide if you like. What are the essential steps? What classes should I inherit from if I want to write a plugin to the data-slicer package? Could you please include this information in your docs? From my perspective this can be held pretty short (e.g. something like https://psyplot.readthedocs.io/projects/psyplot-gui/en/latest/plugins.html), but it should be mentioned somewhere as an initial starting point.

**Comment by kuadrat** [comment]
Hi @Chilipp , this is exactly what I had in mind with issue #14 :) Since you explicitly mention it here, I will add the joss tag to it and start working on it next.

**Comment by kuadrat** [comment]
Hi again, @Chilipp, 387dae7 should address your latest suggestion. It turned out a little longer than expected, hopefully making things quite clear. I'd be happy to hear your thoughts!

**Comment by Chilipp** [comment]
wow! that's indeed very detailed :smile: Thanks @kuadrat!
