### ISSUE TITLE
Data formats compatible with data_slicer

### ISSUE THREAD

**Issue by sabinomaggi** [kuadrat/data-slicer#4]
Hi @kuadrat one of the main shortcoming of the documentation is the absence of any description about the format of the data that `data-slicer` (and/or `PIT`) can process, as well as about how make PIT read a generic datafile besides those distributed with the package. 
A discussion on how to convert one's own data to a format that data-slicer/PIT can read could also be a welcome addition.
And since we are talking about files, why not to allow PIT to read a data file from the command line?

**Disclaimer**

This issue is part of the JOSS review in [https://github.com/openjournals/joss-reviews/issues/2969](https://github.com/openjournals/joss-reviews/issues/2969)

**Comment by kuadrat** [comment]
Hi @sabinomaggi and thanks for your feedback. Judging from the more detailed description in your review report, I could fully understand if this lack of documentation on my side has let to a considerable amount of frustration - I know it would have for me. So I want to thank you for your dedication in finding the way to do it from the source code and apologize for the hassle.

Since all testers so far have been using compatible data formats to begin with and documentation principally exists ([though it is sparse and not at all obvious where](https://data-slicer.readthedocs.io/en/latest/data_slicer.html#data_slicer.dataloading.Dataloader_3dtxt)), this issue has flown under the radar.

I'm going to add a section to a more visible part of the documentation.

**Comment by sabinomaggi** [comment]
@kuadrat This is exactly what I tried to do at the beginning (I usually prefer text data files over binary formats), but it was very cumbersome to do and at the end I decided that for my own testing a pickle was far easier and faster. 
The problem is that searching through an API is not a job that everyone can do. I think it would be far better for the success of your package to write one (or more) tutorials describing how to handle data sets and how to put together the many data-slicer functions to visualize one's own data. My two cents...

**Comment by kuadrat** [comment]
Hi @sabinomaggi,
> I think it would be far better for the success of your package to write one (or more) tutorials  describing how to handle data sets and how to put together the many data-slicer functions to visualize one's own data. 

I absolutely agree.
Explanations and a tutorial on data formats have been added [here](https://data-slicer.readthedocs.io/en/latest/data_format.html).
Also, there is now some more intuitive example data that can be loaded with ``mw.brain()``, referenced in two places in the documentation.
I plan on extending the documentation with an additional step-by-step guide on working with this example data.

Furthermore, the newest version (0.0.12) gives you the functionality that you rightfully expected, namely loading a file directly when launching ``PIT`` from the command line.

**Comment by Chilipp** [comment]
hey @kuadrat! thank you very much for adding this content. I agree with @sabinomaggi that this is important. 

> Explanations and a tutorial on data formats have been added here.
> Also, there is now some more intuitive example data that can be loaded with mw.brain(), referenced in two places in the documentation.

I also recommend to include how to plot data directly, without using a local pickle or text file. From what I got from your code, this can be done via something like `pit.prepare_data(my_data, axes)`?

I found another issue with your new documentation that I'll reference in another issue, though

**Comment by sabinomaggi** [comment]
> Furthermore, the newest version (0.0.12) gives you the functionality that you rightfully expected, namely loading a file directly when launching PIT from the command line.

Yes, now `pit` can load binary and text files from the comand line.
